### ISSUE TITLE
Just Bump Tested Up To?

### ISSUE THREAD

**Issue by GaryJones** [getherbert/ship#1]
Interesting application, thanks! Not tested a full release yet, but the sign-up and sync of a repo seemed to go smoothly.

One thing that's possible when handling the SVN directly is to just update the relevant readme.txt with an updated `Tested up to:` number, without having to do a new release. Is there a similar way (perhaps adding more triggers to the webhook?) where I can update readme.txt in GitHub, and have it update the relevant readme.txt on WP.org so that it's marked as being supported on the latest WP release?

**Comment by lilmike** [comment]
+1 -- I was going to open an issue on a similar topic:
It would be nice if the github master would sync with the svn trunk, or at least, if not that, that the readme would. I was in the same situation, having to update the readme manually on svn... kind of puts a damper on not having to have the svn repo around anymore :P.
Thanks!
-Michael.

**Comment by shivapoudel** [comment]
+1

**Comment by lilmike** [comment]
_bump_... this issue seems to have gotten lost somehow :P.
-Michael.
