### ISSUE TITLE
Has ship been abandoned?

### ISSUE THREAD

**Issue by ozthegreat** [getherbert/ship#17]
Nothing seems to have been done in a while and no new issues replied to, is it officially abandoned? I'd happily contribute to it or take it over if so

**Comment by tyrann0us** [comment]
Hi @jasonagnew,
we'd really appreciate if you could take a look at some of the issues here like this one, #13, #14, #15, #16.
Thanks a lot!

**Comment by meglio** [comment]
@ozthegreat did you take it over eventually?

**Comment by ozthegreat** [comment]
Afraid not. Looks like it’s been complete abandoned
