### ISSUE TITLE
Default SVN URL

### ISSUE THREAD

**Issue by GaryJones** [getherbert/ship#2]
Three points here:
- Instead of using a input placeholder attribute, could you populate the SVN repo URL field with a value? That makes it easier to edit without having to type the whole lot. 
- The `http://plugins.svn.wordpress.org/` section is going to be consistent for everyone, so could that be added as a prefix outside of the field?
- The default SVN repo path seems to be `{github-user-name}-{github-repo-name}`. I think it's more common to have just the repo name for both VCSs the same i.e. the default SVN repo name would basically just be `{github-repo-name}`.

**Comment by robneu** [comment]
+1 to this. The placeholder is a little confusing since you can't copy it in any way. Having an incorrect URL that could be edited would probably be more useful than a placeholder that gets hidden as soon as you start typing.

**Comment by jasonagnew** [comment]
Thanks for feedback, we've changed that now.
