### ISSUE TITLE
Test SVN credentials

### ISSUE THREAD

**Issue by GaryJones** [getherbert/ship#3]
When entering SVN credentials (username and password), it would be nice to be able to test them, manually or automatically, before the webhook can be applied. Can an SVN checkout or other action behind the scenes be done that uses the credentials, to see if it was successful?

That would also allow the SVN repo path (ie. plugin slug) to be tested to see if it actually exists etc.

**Comment by jasonagnew** [comment]
I agree, I'll mark this as an enhancement and we'll add it this week.

**Comment by shivapoudel** [comment]
+1

**Comment by vincentschroeder** [comment]
+1
