### ISSUE TITLE
Note Sync Method After Connecting a Repo

### ISSUE THREAD

**Issue by robneu** [getherbert/ship#4]
This looks pretty handy! Thanks for making it. One thought I had when I was testing a connection was that it would probably be a good idea to note somewhere within the actual application that the sync won't take place until a new release is tagged on GitHub.

I signed up really quickly and didn't see anything about exactly how the releases would be handled until I completely signed out of the app. Without knowing that, I wasn't sure if it would be auto synced, synced based on branch, or on some kind of a running schedule or something.

**Comment by jasonagnew** [comment]
We've updated the message. I think along with this we are going to add a way to sync an old release. Incase you want to use Ship but have no real release to create another release.
