### ISSUE TITLE
What is the correct way to set up WordPress SVN?

### ISSUE THREAD

**Issue by wolffe** [getherbert/ship#7]
Should I append /trunk at the end of my WordPress SVN URL?

Or should I have the complete directory structure inside my GitHub repository?

assets/
branches/
tags/
trunk/

**Comment by jasonagnew** [comment]
Your URL would be without the trunk, for example:

http://plugins.svn.wordpress.org/socializr

And no need to have trunk etc in your folder, heres a plugin we tested it with:

https://github.com/bigbitecreative/wordpress-socializr

**Comment by wolffe** [comment]
Great. Thank you.
